jdbc.driver=com.mysql.cj.jdbc.Driver
jdbc.url=jdbc:mysql://localhost:3306/e3?useSSL=false&serverTimezone=UTC&characterEncoding=utf8&allowPublicKeyRetrieval=true
jdbc.username=OwO
jdbc.password=zy142857

hikari.maximum-pool-size=10
hikari.minimum-idle=5
hikari.connection-timeout=30000