# 数据库配置文件（密码已加密）
db.url=jdbc:mysql://localhost:3306/dblessondesign
db.params=useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf8
db.username=root
db.password.encrypted=xGCynXAx/S+5rqQ9sWl8Cg==
db.encryption.algorithm=AES
